### ISSUE TITLE
Do not open compressed Executables.

### ISSUE THREAD

**Issue by AraHaan** [Polymaker/resource-explorer#1]
The reason why it is bad to open Compressed executables is because someone would try to modify and saving it corrupting the whole thing. Instead do not allow opening them until they are decompressed.

**Comment by Polymaker** [comment]
I'm not sure I understand what you mean by compressed executable.

**Comment by AraHaan** [comment]
There is a better explanation of Executable compression on the UPX Website that is now hosted on github.
