### ISSUE TITLE
Add support for Executables made in C++.

### ISSUE THREAD

**Issue by AraHaan** [Polymaker/resource-explorer#2]
It would be nice if this also supported unmanaged C++. There is also managed that uses the .NET Framework though.

Why?
Well full Windows PE support is actually a good thing. Look at UPX for example it supports all sorts of formats and Compression of .NET Executables are planned for that as well.

**Comment by Polymaker** [comment]
It is, or more accurately, it will. I don't know if you've read the project description or looked at the code but it will support both managed and unmanaged DLLs.

**Comment by AraHaan** [comment]
What about exe files as well since they are similar just with a few different flag settings on it?

**Comment by Polymaker** [comment]
Yes I should have said executable instead of DLL. They work pretty much the same and my code already works for both.
